apiVersion: apps/v1
kind: Deployment
metadata:
  name: elearning-backend
  labels:
    app: elearning-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elearning-backend
  template:
    metadata:
      labels:
        app: elearning-backend
    spec:
      containers:
        - name: elearning-backend
          image: elearning-backend:latest  # ← ton image Docker
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          # ✅ Variables NON-sensibles (configmap)
          envFrom:
            - configMapRef:
                name: elearning-configmap
          # ✅ Variables SENSIBLES (secret)
          env:
            - name: URL_MONGO
              valueFrom:
                secretKeyRef:
                  name: elearning-secret
                  key: URL_MONGO
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: elearning-secret
                  key: JWT_SECRET
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: elearning-secret
                  key: EMAIL_USER
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: elearning-secret
                  key: EMAIL_PASS