apiVersion: apps/v1
kind: Deployment
metadata:
  name: elearning-backend
  labels:
    app: elearning-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elearning-backend
  template:
    metadata:
      labels:
        app: elearning-backend
    spec:
      nodeSelector:
        kubernetes.io/hostname: master   # ✅ Force le pod sur master (accès internet)
      containers:
        - name: elearning-backend
          image: anasmnasri/elearning-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: elearning-configmap
          env:
            - name: URL_MONGO
              valueFrom:
                secretKeyRef:
                  name: elearning-secret
                  key: URL_MONGO
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: elearning-secret
                  key: JWT_SECRET
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: elearning-secret
                  key: EMAIL_USER
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: elearning-secret
                  key: EMAIL_PASS
