apiVersion: apps/v1
kind: Deployment
metadata:
  name: elearning-backend
  labels:
    app: elearning-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elearning-backend
  template:
    metadata:
      labels:
        app: elearning-backend
    spec:
      containers:
        - name: elearning-backend
          image: nouran10/elearning-backend:latest   # 🔁 remplace par ton image buildée
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: elearning-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: elearning-config
                  key: PORT
            - name: URL_MONGO
              valueFrom:
                secretKeyRef:
                  name: elearning-secret
                  key: URL_MONGO
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: elearning-secret
                  key: JWT_SECRET
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: elearning-secret
                  key: EMAIL_USER
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: elearning-secret
                  key: EMAIL_PASS
          readinessProbe:
            httpGet:
              path: /api/health      # adapte si tu as un endpoint /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: Always