apiVersion: v1
kind: Secret
metadata:
  name: elearning-secret
type: Opaque
stringData:
  URL_MONGO: "mongodb+srv://mnasrianas5:Q%21c4bi-R%25zMjv_N@e-learning.4xo68wt.mongodb.net/elearning-db?retryWrites=true&w=majority&appName=E-learning"
  JWT_SECRET: "your_super_secret_jwt_key_here"
  EMAIL_USER: "eelearninglanguage@gmail.com"
  EMAIL_PASS: "uxzfbmpvivrpyzrt"