[master]
master-node ansible_host=192.168.205.3 ansible_user=anas ansible_ssh_private_key_file=/home/anas/Desktop/Deployement/ansible/master.pem

[worker]
worker-node ansible_host=192.168.205.4 ansible_user=anas ansible_ssh_private_key_file=/home/anas/Desktop/Deployement/ansible/worker.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3
